# Generated by Django 5.2.14 on 2026-07-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(blank=True, choices=[('aluguel', 'Aluguel'), ('venda', 'Venda')], db_index=True, max_length=10, null=True)),
                ('bairro', models.CharField(blank=True, max_length=250, null=True)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quartos', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('origem_carga', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_cliente', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('closed', 'Fechada')], db_index=True, default='active', max_length=10)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imoveis_recomendados', models.ManyToManyField(blank=True, related_name='conversas', to='iamoveis.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'Cliente'), ('assistant', 'Assistente')], max_length=10)),
                ('conteudo', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='iamoveis.conversa')),
            ],
        ),
    ]
