# Generated by Django 5.2.14 on 2026-07-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='message_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
